### PR TITLE
Adding `Ascent` theme

### PR DESCRIPTION
**Pull request by mWalrus**
Please let me know if I've missed anything :)

### CODE REVIEW

**Comment by mautamu** [comment]
Looks good; you might want to see https://github.com/leftwm/leftwm/issues/652 about `echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe`in `up` and `down`. You can either set leftwm_versions should be '<3.0.0' or change to calling leftwm-command and then have leftwm_versions be `>0.2.7' (might be 0.2.8?).

**Comment by mWalrus** [comment]
I've updated the theme to use `leftwm-command` instead of piping, and updated my local version of leftwm to `0.3.0` to check that it works, and it does. Is it sufficient to change the `leftwm_versions` in `known.toml` to just `>0.2.7` or should I have it be `^0.2.8`?

**Comment by mWalrus** [comment]
Reread your comment and updated accordingly :)

**Comment by mWalrus** [comment]
@mautamu does this look good?

**Comment by mautamu** [comment]
Oh, apologies for the delay. Yea, this looks good to me. Tagging @AethanFoot for merge.

**Review by mautamu — APPROVED** [review]

**Pull request merged**
