### PR TITLE
Added doublabar

### PR DESCRIPTION
**Pull request by PeterDauwe**
i hope this is the right way. (first time doing this)
Made a doublebar-theme

### CODE REVIEW

**Comment by VuiMuich** [comment]
Hi, thanks for this submission.
Tbh I am not terribly familiar with the community themes my self so far, but from scumming through the diffs of this PR on mobile I noticed a few things:
ideally the theme contains only configs and scripts that actually define the look and feel.

Did you know you can have a 'local' pair of `up`/`down` scripts that start processes you like to have in your workflow, but would to have them with any theme. Things like `sxhkd` or in my case `unclutter` are best to be kept there.
You sure are welcome to open a '**show and tell**' discussion for some nice scripts you use though.

**Comment by AethanFoot** [comment]
I mad a guide a while ago, https://github.com/AethanFoot/leftwm-community-themes/wiki/Sharing, where the theme is added as a submodule.
Thanks!

**Comment by VuiMuich** [comment]
> I mad a guide a while ago, https://github.com/AethanFoot/leftwm-community-themes/wiki/Sharing, where the theme is added as a submodule. Thanks!

This guide looks great. Who has write permission for the community-theme wiki? @mautamu @lex148 ?

**Comment by mautamu** [comment]
Looks fantastic! I don’t think I have write access. 

Cheers,
Mau

**Pull request merged**
