### PR TITLE
Bump Molese them to v2.1.0

### PR DESCRIPTION
**Pull request by m0lese**
Signed-off-by: molese <molese@protonmail.com>

### CODE REVIEW

**Comment by mautamu** [comment]
Does known.toml need updated?

**Review by mautamu — APPROVED** [review]
Looks good to me, thanks for the theme!

**Comment by m0lese** [comment]
Oh, it hasn't been merged yet!! I wonder why.

**Comment by VuiMuich** [comment]
:relaxed: us being lazy, I am sorry we made you wait unreasonably...

**Pull request merged**
