### PR TITLE
Update Epitaph screenshot

### PR DESCRIPTION
**Pull request by VentGrey**
The current screenshot presented is from a **VERY** old Epitaph version :thinking: I also tried updating the submodule with no success. Any tips on how to proceed on that? :3

### CODE REVIEW

**Comment by VuiMuich** [comment]
:thinking: have you tried `git submodule sync && git submodule update --init --recursive`?
I am unsure as well if submodules should be up to date in the remote or only locally.

**Comment by VentGrey** [comment]
I already tried that, that inits / syncs the submodules locally but doesn't register changes to make a PR :c

**Comment by VentGrey** [comment]
Managed to update the Epitaph submodule :)  waiting for your feedback.

**Comment by VuiMuich** [comment]
So what's the trick then?

**Pull request merged**
